import { KeyConfig } from "@/types/keyboard";

export const keyboardLayout: KeyConfig[][] = [
    [
        { label: "esc", width: "lg", align: "baseline-start" },
        { label: "F1", fn: true },
        { label: "F2", fn: true },
        { label: "F3", fn: true },
        { label: "F4", fn: true },
        { label: "F5", fn: true },
        { label: "F6", fn: true },
        { label: "F7", fn: true },
        { label: "F8", fn: true },
        { label: "F9", fn: true },
        { label: "F10", fn: true },
        { label: "F11", fn: true },
        { label: "F12", fn: true },
        { label: " ", fn: true }
    ],
    [
        { label: "`", top: "~", bottom: "`" },
        { top: "!", bottom: "1" },
        { top: "@", bottom: "2" },
        { top: "#", bottom: "3" },
        { top: "$", bottom: "4" },
        { top: "%", bottom: "5" },
        { top: "^", bottom: "6" },
        { top: "&", bottom: "7" },
        { top: "*", bottom: "8" },
        { top: "(", bottom: "9" },
        { top: ")", bottom: "0" },
        { top: "_", bottom: "-" },
        { top: "+", bottom: "=" },
        { label: "delete", width: "lg", align: "baseline-end" }
    ],
    [
        { label: "tab", width: "lg", align: "baseline-start" },
        { label: "Q", },
        { label: "W" },
        { label: "E" },
        { label: "R" },
        { label: "T" },
        { label: "Y" },
        { label: "U" },
        { label: "I" },
        { label: "O" },
        { label: "P" },
        { top: "{", bottom: "[" },
        { top: "}", bottom: "]" },
        { top: "|", bottom: "\\" }
    ],
    [
        { label: "capslock", width: "xl", align: "baseline-start", fn: true },
        { label: "A", },
        { label: "S" },
        { label: "D" },
        { label: "F" },
        { label: "G" },
        { label: "H" },
        { label: "J" },
        { label: "K" },
        { label: "L" },
        { top: ":", bottom: ";" },
        { top: "\"", bottom: "\'" },
        { label: "return", width: "xl", align: "baseline-end" },
    ],
    [
        { top: "⇧", bottom: "shift", width: "xll", align: "baseline-start" },
        { label: "Z", },
        { label: "X" },
        { label: "C" },
        { label: "V" },
        { label: "B" },
        { label: "N" },
        { label: "M" },
        { top: "<", bottom: "," },
        { top: ">", bottom: "." },
        { top: "?", bottom: "/" },
        { top: "⇧", bottom: "shift", width: "xll", align: "baseline-end" },
    ],
    [
        { label: "fn", align: "baseline-start" },
        { top: "⌃", bottom: "control", align: "baseline-start" },
        { top: "⌥", bottom: "option", align: "baseline-start" },
        { top: "⌘", bottom: "command", width: "cm", align: "baseline-start" },
        { label: "", width: "space" },
        { top: "⌘", bottom: "command", width: "cm", align: "baseline-end" },
        { top: "⌥", bottom: "option", align: "baseline-end" },
        { label: "l" },
        { label: "d" },
        { label: "r" },
    ],
];
